properly define build args

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -14,9 +14,10 @@ RUN pnpm install --frozen-lockfile --ignore-scripts
 
 FROM base AS builder
 WORKDIR /app
-# Note:FLASK_URL needs to be baked into the container, rebuild container
-# with deployment specifics for Fargate/ECS
-RUN [-n "$FLASK_URL" ] || { echo "ERROR: Missing required env_var: FLASK_URL"; exit 1; }
+ARG FLASK_URL
+ARG NEXT_PUBLIC_GLOBUS_CLIENT_ID
+RUN [ -n "$FLASK_URL" ] || { echo "ERROR: Missing required env_var: FLASK_URL"; exit 1; }
+RUN [ -n "$NEXT_PUBLIC_GLOBUS_CLIENT_ID" ] || { echo "ERROR: Missing required env_var: NEXT_PUBLIC_GLOBUS_CLIENT_ID"; exit 1; }
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 RUN pnpm build
